name: Tattour-Server-Dev CD
on:
  push:
    branches: [ "dev" ]

env:
  S3_BUCKET_NAME: tattour-storage

jobs:
  build:
    name: Code deployment
    runs-on: ubuntu-latest

    steps:
    
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: make application.properties
      run: |
        #mkdir ./server/src/main/resources
        cd ./server/src/main/resources
        touch ./application.yaml
        echo "${{ secrets.TATTOUR_DEV_APPLICATION }}" >> ./application.yaml
        cat ./application.yaml
      shell: bash
      

    - name: Grant execute permission for gradlew
      run: chmod +x ./server/gradlew
      
    - name: Build with Gradle
      run: |
        cd ./server
        ./gradlew clean build -x test

    - name: Make Directory
      run: mkdir -p deploy
      
    - name: Copy Jar
      run: cp ./server/build/libs/*.jar ./deploy
    
    - name: Copy appspec.yml
      run: cp appspec.yml ./deploy

    - name: Copy script
      run: cp ./scripts/deploy_dev.sh ./deploy
      
    - name: Make zip file
      run: zip -r ./tattour_server_dev.zip ./deploy
      shell: bash
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_CODEDEPLOY_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_CODEDEPLOY_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./tattour_server_dev.zip s3://tattour-storage\
      
    # Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CODEDEPLOY_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CODEDEPLOY_SECRET_ACCESS_KEY }}
      run:
        aws deploy create-deployment
        --application-name tattour-codeDepoly-test
        --deployment-group-name tattour-codeDepoly-test-group
        --file-exists-behavior OVERWRITE 
        --s3-location bucket=tattour-storage,bundleType=zip,key=tattour_server_dev.zip
        --region ap-northeast-2
